<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CURA__AppointmentConfirmation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9e215486-1c03-4c0f-aa67-35b83b0cf2d1</testSuiteGuid>
   <testCaseLink>
      <guid>8f5f18d5-496c-4f36-a1aa-22ba7292dcf6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CURA_Make_Appointment/TC_CURA_AppointmentConformation_002</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>65e0373c-a51a-4757-b89e-a1b3d47810b6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data_CURA_ExcellSheet_2/DD_CURA_TestData_Sheet_2</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>200fd3f1-1bba-4060-a913-8e6768c653d4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData_CURA_AppointmentConfirmation_sheet/DD_MakeAppointment_1</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>65e0373c-a51a-4757-b89e-a1b3d47810b6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Facility</value>
         <variableId>c88e6c15-cd70-4dd0-854d-b8f36c195d46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>65e0373c-a51a-4757-b89e-a1b3d47810b6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>comment</value>
         <variableId>215b1778-e89b-47bb-8170-c35ff9ff5ad6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
